### ISSUE TITLE
Inorder PreOrder and PostOrder Tree Traversal 

### ISSUE THREAD

**Issue by Kali-13** [iamAnki/CPP-Programs-#531]
Assign it to me so that I can add these algorithms.

**Comment by rohan12k** [comment]
I can do it.

**Comment by Vivek7038** [comment]
Please assign this to me  as i know how to write clean code.I will also add comments at every step whenever requuired .
i will also add a md file with essential notes and references .

**Comment by janvichoudhary08** [comment]
hey please  assign me  this issue as a part of  hacktoberfest.

**Comment by diksha0149** [comment]
Hii @Kali-13 Please assign me this issue. I try to write as best explanation as I can.
Thank You.

**Comment by sharyu04** [comment]
Hii, I will write a neat easy to understand explanation and code for this issue, please assign me this.
